### ISSUE TITLE
Could not load dynamic library 'libcuda.so.1'

### ISSUE THREAD

**Issue by tenshis** [minimaxir/gpt-2-cloud-run#17]
When running the docker image, I receive the following cuda error. I have built the image using the normal tensorflow==1.15, but as far as I know cuda is only required for tensorflow on GPU?

```
2020-01-16 12:58:56.907133: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-01-16 12:58:56.907168: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2020-01-16 12:58:56.907187: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (a88f782966c0): /proc/driver/nvidia/version does not exist
```

**Comment by bhavikshah1995** [comment]
Did you find a solution for this?

**Comment by cosmin-novac** [comment]
I'm afraid not, and in the meanwhile I moved away from cloud run

**Comment by bhavikshah1995** [comment]
Update: I was getting this error when trying to use Tensorflow with GPU on Ubuntu 18.04, and was able to resolve the issue by following the instructions on https://www.tensorflow.org/install/gpu

**Comment by jackzhou121** [comment]
I have the same problem with docker image tensorflow==1.15.0
